<input type="hidden" id="theme_type" name="theme_type" value="<{$theme_type|default:''}>">
<input type="hidden" id="theme_width" name="theme_width" value="<{$theme_width|default:''}>">
<input type="hidden" id="base_color" name="base_color" value="<{$base_color|default:''}>">
<input type="hidden" id="lb_color" name="lb_color" value="<{$lb_color|default:''}>">
<input type="hidden" id="cb_color" name="cb_color" value="<{$cb_color|default:''}>">
<input type="hidden" id="rb_color" name="rb_color" value="<{$rb_color|default:''}>">
<input type="hidden" id="lb_width" name="lb_width" value="<{$lb_width|default:''}>">
<input type="hidden" id="cb_width" name="cb_width" value="<{$cb_width|default:''}>">
<input type="hidden" id="rb_width" name="rb_width" value="<{$rb_width|default:''}>">
<input type="hidden" id="clb_width" name="clb_width" value="<{$clb_width|default:''}>">
<input type="hidden" id="crb_width" name="crb_width" value="<{$crb_width|default:''}>">
<input type="hidden" id="margin_top" name="margin_top" value="<{$margin_top|default:''}>">
<input type="hidden" id="font_size" name="font_size" value="<{$font_size|default:''}>">
<input type="hidden" id="margin_bottom" name="margin_bottom" value="<{$margin_bottom|default:''}>">
<input type="hidden" id="font_color" name="font_color" value="<{$font_color|default:''}>">
<input type="hidden" id="link_color" name="link_color" value="<{$link_color|default:''}>">
<input type="hidden" id="hover_color" name="hover_color" value="<{$hover_color|default:''}>">